### ISSUE TITLE
need some help on how to set blips and locations 

### ISSUE THREAD

**Issue by NOMADxSMOKEY** [Giana/g-drugselling#9]
hello how are you doing thank you for the amazing script!! i am fairly new to this fivem stuff ive been working on a server by my self watching videos and stuff but its still really confusing..i have your script installed properly with no errors but what im strugling with is hoewto set up locations with blips as well and selling.

**Comment by Giana** [comment]
In the config.lua you will find all the default locations laid out along with comments I wrote saying what each field indicates and how you can customize it to your liking. In there, you can also add new locations if you wish.

If you have any specific questions still, let me know, but reading through the config should help.
